name: Deploy to wakaba

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_to_wakaba:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-northeast-1
      AWS_ROLE_TO_ASSUME: arn:aws:iam::616657986447:role/romira_service_manage_bot_v2_github_actions_deploy_role
      INSTANCE_ID: mi-0853a7fab289ebfad
      SOURCE_FILE_PATH: Cargo.toml
      DESTINATION_FILE_PATH: /home/romira/Cargo.toml

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}

      - name: Deploy to wakaba
        run: |
          aws ssm send-command \
          --document-name 'AWS-RunShellScript' \
          --instance-ids ${{ env.INSTANCE_ID }} \
          --parameters 'commands=[
          "bash -c \"touch ssm-send-command-test.txt\""
          ]' \
          --timeout-seconds 60 \
          --region ap-northeast-1
